In [1]:
import pandas as pd
import numpy as np
import requests

# Get power meter data

<img src="picture/powerMeterData.jpg" width="60%">

In [2]:
#可以從chrome的DevTool裡面的network觀看, data form裡面的參數作為payload進行post
#參考連結1: https://stackoverflow.com/questions/56183029/how-to-read-data-from-from-web-link-with-drop-down-fields-using-python
#參考連結2: https://stackoverflow.com/questions/54789508/using-python-requests-module-with-dropdown-options

payload = {'ctg': 'all',
           'dt1': '2019/08/09',
           'ok': '查詢'}

r = requests.post('http://140.112.166.97/power/fn4/report2.aspx', data = payload)
tables = pd.read_html(r.text)

In [3]:
tables[0]

                                                   0
0  查詢標的：  -----依用電分區-----  總配電站  海洋所饋線  推廣中心饋線  管...

In [4]:
tables[1]

,0,1,2,3,4,5,6,7,8,9,...,205,206,207,208,209,210,211,212,213,214
0,國立台灣大學 108年8月9日 全校館舍 用電日報表 (單位：度),國立台灣大學 108年8月9日 全校館舍 用電日報表 (單位：度),國立台灣大學 108年8月9日 全校館舍 用電日報表 (單位：度),國立台灣大學 108年8月9日 全校館舍 用電日報表 (單位：度),國立台灣大學 108年8月9日 全校館舍 用電日報表 (單位：度),國立台灣大學 108年8月9日 全校館舍 用電日報表 (單位：度),國立台灣大學 108年8月9日 全校館舍 用電日報表 (單位：度),國立台灣大學 108年8月9日 全校館舍 用電日報表 (單位：度),國立台灣大學 108年8月9日 全校館舍 用電日報表 (單位：度),國立台灣大學 108年8月9日 全校館舍 用電日報表 (單位：度),...,國立台灣大學 108年8月9日 全校館舍 用電日報表 (單位：度),國立台灣大學 108年8月9日 全校館舍 用電日報表 (單位：度),國立台灣大學 108年8月9日 全校館舍 用電日報表 (單位：度),國立台灣大學 108年8月9日 全校館舍 用電日報表 (單位：度),國立台灣大學 108年8月9日 全校館舍 用電日報表 (單位：度),國立台灣大學 108年8月9日 全校館舍 用電日報表 (單位：度),國立台灣大學 108年8月9日 全校館舍 用電日報表 (單位：度),國立台灣大學 108年8月9日 全校館舍 用電日報表 (單位：度),國立台灣大學 108年8月9日 全校館舍 用電日報表 (單位：度),國立台灣大學 108年8月9日 全校館舍 用電日報表 (單位：度)
1,時間/館舍,數學館,新數學研究中心,-新生大樓-,生化所,電機一館,化學館,貴儀中心氦液化機用電,化學館(不含貴儀中心氦液化機用電),積學館,...,明達館,明達館停車場,明達2F保管組場地,生科館停車場,生科館,徐州校區國際會議廳,法學院社科圖書館,農業試驗場,種子研究室,人工氣候室
2,分區編號,N1_1A,N1_1A,N1_1A,N1_1B,N1_1B,N1_1B,N1_1B,N1_1B,N1_1B,...,N9_7E,N9_7E,N9_7E,N9_7F,N9_7F,NB_1M,NB_1M,NS_9G,NS_9G,NS-9G
3,0~1,20.25,20.06,13.31,88.64,98.91,398.61,0.97,397.64,289.85,...,68.78,2.44,4.21,2.25,432.78,1.52,12.52,---,---,---
4,1~2,20.25,20.07,13.00,88.03,98.71,400.03,1.05,398.98,286.79,...,68.89,2.42,4.06,2.27,425.39,1.38,12.23,---,---,---
5,2~3,20.69,20.08,13.13,86.10,99.91,392.46,0.97,391.49,276.63,...,68.78,2.47,4.16,2.25,422.97,1.37,11.91,---,---,---
6,3~4,20.68,20.03,12.93,89.73,99.84,388.36,3.17,385.19,269.43,...,68.35,2.45,4.91,2.25,421.34,1.68,12.76,---,---,---
7,4~5,20.75,20.23,13.50,88.67,99.47,388.80,0.97,387.83,270.08,...,67.37,2.50,4.36,2.25,421.25,1.87,12.38,---,---,---
8,5~6,20.75,20.12,12.69,87.14,100.94,391.65,1.06,390.59,270.35,...,67.16,2.55,4.37,2.26,422.08,1.82,12.31,---,---,---
9,6~7,21.63,20.11,12.75,91.04,99.25,392.84,0.97,391.87,268.26,...,63.64,2.45,4.38,2.25,432.66,1.45,12.92,---,---,---
10,7~8,21.19,20.15,72.44,95.68,99.72,389.65,1.05,388.60,267.28,...,65.63,2.44,4.25,2.25,448.84,1.49,10.56,---,---,---
11,8~9,22.68,20.93,58.25,97.11,99.44,391.58,3.04,388.54,266.41,...,66.66,2.39,4.16,2.25,485.35,1.54,12.39,---,---,---
12,9~10,26.39,21.60,54.44,96.52,99.40,390.12,1.05,389.07,272.23,...,68.67,2.41,4.25,2.25,538.56,1.43,12.43,---,---,---
13,10~11,28.18,21.59,45.93,94.00,100.25,420.03,0.95,419.08,291.00,...,70.73,2.82,4.31,2.24,621.04,1.80,12.34,---,---,---
14,11~12,27.69,21.47,47.75,96.90,99.82,421.65,1.05,420.60,302.79,...,72.54,4.02,4.07,2.25,641.41,1.47,13.83,---,---,---
15,12~13,25.49,21.60,45.32,98.29,100.00,428.25,1.01,427.24,332.03,...,74.53,2.39,4.25,2.23,641.24,1.48,12.97,---,---,---
16,13~14,26.57,21.37,46.12,107.56,99.25,436.67,3.07,433.60,353.01,...,78.34,2.39,3.84,2.25,681.87,1.45,12.35,---,---,---
17,14~15,32.00,20.69,47.06,108.34,98.09,445.24,1.03,444.21,390.89,...,80.45,2.36,4.53,2.23,711.46,1.51,9.83,---,---,---
18,15~16,35.00,20.52,47.44,111.13,98.87,468.06,0.95,467.11,393.10,...,86.66,2.42,4.53,2.25,763.94,1.85,9.64,---,---,---
19,16~17,34.69,20.62,45.19,106.22,97.94,474.78,1.03,473.75,398.87,...,83.35,2.53,4.43,2.24,783.01,1.47,11.58,---,---,---
20,17~18,32.62,20.19,41.12,103.32,98.10,465.49,0.96,464.53,398.59,...,86.21,2.78,4.07,2.23,747.77,1.42,14.01,---,---,---
21,18~19,29.25,20.27,14.13,99.57,98.03,471.35,3.11,468.24,387.84,...,82.17,2.50,4.08,2.24,671.85,1.39,13.83,---,---,---
22,19~20,27.81,20.29,13.75,95.40,100.00,478.86,0.95,477.91,374.49,...,78.48,2.52,4.05,2.26,656.40,1.40,12.76,---,---,---
23,20~21,27.82,20.43,13.44,95.78,98.81,471.63,1.03,470.60,345.57,...,79.42,2.52,4.21,2.24,641.32,1.71,12.86,---,---,---
24,21~22,26.49,20.43,14.56,97.19,101.12,462.90,0.95,461.95,326.83,...,80.79,2.56,4.12,2.23,626.27,1.40,12.67,---,---,---
25,22~23,24.94,20.10,13.62,96.16,100.97,433.58,1.05,432.53,300.82,...,83.30,2.56,4.18,2.24,491.45,1.40,12.62,---,---,---
26,23~24,24.07,20.01,12.75,95.53,100.00,424.39,0.95,423.44,293.33,...,75.94,2.55,4.11,2.23,464.77,1.41,11.53,---,---,---
27,合計,617.88,492.96,724.62,2314.05,2386.84,10226.98,32.39,10194.59,7626.47,...,1786.84,61.44,101.89,53.89,13595.02,36.71,295.23,---,---,---

# Get weather data

<img src="picture/weatherHistoricalData.jpg" width="70%">

In [5]:
url = 'http://e-service.cwb.gov.tw/HistoryDataQuery/DayDataController.do?command=viewMain&station=466920&stname=%25E8%2587%25BA%25E5%258C%2597&datepicker=2019-08-08'
pd.read_html(url, encoding='utf8')[1]

   Unnamed: 0_level_0     Press            temperature    dew point      RH  \
           觀測時間(hour) 測站氣壓(hPa) 海平面氣壓(hPa)       氣溫(℃)      露點溫度(℃) 相對溼度(%)
              ObsTime   StnPres    SeaPres Temperature Td dew point      RH
0                   1     993.6      997.0        28.8         28.1      96
1                   2     993.3      996.7        28.7         27.8      95
2                   3     993.4      996.8        29.0         27.6      92
3                   4     992.8      996.2        28.2         27.5      96
4                   5     992.6      996.0        28.0         27.5      97
5                   6     992.9      996.3        28.3         27.7      97
6                   7     992.9      996.3        29.1         28.0      94
7                   8     993.0      996.4        28.5         27.8      96
8                   9     992.9      996.3        30.2         28.4      90
9                  10     992.8      996.2        31.2         28.4      85
10                 11     992.1      995.5        32.8         24.9      63
11                 12     991.6      995.0        32.9         25.0      63
12                 13     990.4      993.8        32.1         26.1      71
13                 14     989.3      992.6        33.3         25.3      63
14                 15     989.8      993.2        28.5         27.3      93
15                 16     989.7      993.1        28.1         27.6      97
16                 17     989.7      993.1        28.2         27.7      97
17                 18     989.2      992.6        28.6         28.2      98
18                 19     988.9      992.3        27.8         27.4      98
19                 20     988.8      992.2        27.9         27.7      99
20                 21     988.7      992.1        28.1         27.7      98
21                 22     988.7      992.1        27.3         27.3     100
22                 23     987.9      991.3        27.5         27.5     100
23                 24     987.3      990.7        26.4         26.4     100

     WD/WS                                             Precp            \
   風速(m/s) 風向(360degree) 最大陣風(m/s) 最大陣風風向(360degree) 降水量(mm)  降水時數(hr)
        WS            WD    WSGust            WDGust   Precp PrecpHour
0      3.0            90       8.7                70       T       1.0
1      1.7           100       6.0                90       T       1.0
2      2.6            90       7.1               100       T       1.0
3      1.6            80       6.0               100     0.5       1.0
4      1.6            60       3.7               120     0.5       1.0
5      1.3            70       3.1                80     0.5       1.0
6      1.2            70       4.1                80       T       1.0
7      0.8           220       2.7               220     0.5       1.0
8      3.6            60       9.2                80     1.0       1.0
9      2.0            40       8.4                40       T       1.0
10     3.4            70      10.2                50       T       0.3
11     3.1            30      11.4                20     0.0       0.0
12     4.9            20       9.7                40     0.0       0.0
13     2.7            30      11.2                50     0.0       0.0
14     2.4            90      10.2               100     4.0       1.0
15     1.1            50       7.7                40     5.5       1.0
16     1.8           360       7.7                30     2.0       1.0
17     0.7           100       4.2                20       T       1.0
18     2.0            50       8.0                50     1.5       1.0
19     1.2           250       7.2                50       T       1.0
20     0.8           280       4.6               340       T       1.0
21     1.5            20       6.9               340     6.0       1.0
22     0.7            50       6.2                50     1.0       1.0
23     2.1           110       9.7                80     4.5       1.0

   SunShine              visibility   UVI        Cloud
   日照時數(hr) 全天空日射量(MJ/㎡)    能見度(km) 紫外線指數    總雲量(0~10)
   SunShine     GloblRad       Visb   UVI Cloud Amount
0       ...         0.00        ...     0          ...
1       ...         0.00        ...     0          ...
2       ...         0.00        ...     0          ...
3       ...         0.00        ...     0          ...
4       ...         0.00        ...     0          ...
5       0.0         0.00        ...     0          ...
6       0.0         0.08        ...     0          ...
7       0.1         0.28       10.0     1          9.0
8       0.3         1.03       11.0     3          9.0
9       0.2         1.16        ...     5          9.0
10      0.3         1.73       11.0     8          8.0
11      0.4         1.79        ...     9          8.0
12      0.5         2.29        ...    11          9.0
13      0.3         2.21       11.0     9          9.0
14      0.0         0.04        ...     1         10.0
15      0.0         0.00        ...     1         10.0
16      0.0         0.09        6.0     1         10.0
17      0.0         0.00        ...     0          ...
18      0.0         0.00        ...     0          ...
19      ...         0.00        ...     0          ...
20      ...         0.00        ...     0          ...
21      ...         0.00        ...     0          ...
22      ...         0.00        ...     0          ...
23      ...         0.00        ...     0          ...

# Get course schedule

<img src="picture/coursesCalender.jpg" width="60%">

In [6]:
payload = {'SYearDDL': '1081',
           'BuildingDDL': '共同',
           'RoomDDL': '共102',
           'SelectButton': '查詢'}

#要注意把url的https改成http, read_html才能讀取
r = requests.get('http://gra206.aca.ntu.edu.tw/classrm/index.php/acarm/webcr-use-new', params = payload)
tables = pd.read_html(r.text)

In [7]:
tables[3]

,Unnamed: 0,7:100,8:101,9:102,10:203,11:204,12:205,13:206,14:207,15:308,16:309,17:3010,18:25A,19:20B,20:15C,21:10D
0,(日),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,(一),NaN,初級視聽法語一達力安,初級視聽法語一達力安,初級法語會話一達力安,初級法語會話一達力安,日文二上池田晶子,日文二上池田晶子,日文二上池田晶子,拉丁文一上楊明蒼,拉丁文一上楊明蒼,NaN,NaN,NaN,NaN,NaN
2,(二),NaN,NaN,NaN,法文二上歐德尼,法文二上歐德尼,英文作文二上翁怡錚,英文作文二上翁怡錚,英文作文二上翁怡錚,大學國文一林永勝,大學國文一林永勝,大學國文一林永勝,NaN,NaN,NaN,NaN
3,(三),NaN,NaN,日文三上詹兆雯,日文三上詹兆雯,日文三上詹兆雯,英文作文一上曾琦智,英文作文一上曾琦智,英文作文一上曾琦智,英文作文一上曾琦智,英文作文一上曾琦智,英文作文一上曾琦智,NaN,NaN,NaN,NaN
4,(四),NaN,NaN,NaN,英文寫作基礎張 晨,英文寫作基礎張 晨,英文寫作基礎張 晨,NaN,日文二上黃佳鈴,日文二上黃佳鈴,日文二上黃佳鈴,NaN,NaN,NaN,NaN,NaN
5,(五),NaN,法文一上葉麗儀,法文一上葉麗儀,法文二上葉麗儀,法文二上葉麗儀,NaN,阿拉伯文一上初雅士,阿拉伯文一上初雅士,法國電影概論一陳素麗,法國電影概論一陳素麗,NaN,NaN,NaN,NaN,NaN
6,(六),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Get network traffic flow

<img src="picture/mrtgOutput.jpg" width="60%">

<img src="picture/mrtgURL.jpg" width="60%">

In [8]:
#要改寫url才能讀取
#url = 'http://ws5.cc.ntu.edu.tw/cgi-bin/glance.pl?flow/engineering/civil'
url = 'http://ws5.cc.ntu.edu.tw/mrtg_output/flow/engineering/civil/civil.html'
pd.read_html(url, encoding='big5')[1]

             Unnamed: 0                 最大                平均                目前
0  土木系所 => 研圖 Summit24:  131.9 Mb/秒 (1.6%)  21.8 Mb/秒 (0.3%)  17.4 Mb/秒 (0.2%)
1  研圖 Summit24 => 土木系所:  252.9 Mb/秒 (3.2%)  67.1 Mb/秒 (0.8%)  61.9 Mb/秒 (0.8%)

In [9]:
pd.read_html(url, encoding='big5')[2]

             Unnamed: 0                 最大                平均                目前
0  土木系所 => 研圖 Summit24:  141.1 Mb/秒 (1.8%)  32.3 Mb/秒 (0.4%)  17.7 Mb/秒 (0.2%)
1  研圖 Summit24 => 土木系所:  245.4 Mb/秒 (3.1%)  70.9 Mb/秒 (0.9%)  55.5 Mb/秒 (0.7%)